{% set name = "the-way" %}
{% set version = "0.19.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/out-of-cheese-error/the-way/archive/v{{ version }}.tar.gz
  sha256: dbfc7b4a97631d16fc8fb0155bd9d2ba45c22c6e696b0cc7c57d1c35d62e35de

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - the-way --help

about:
  home: https://github.com/out-of-cheese-error/the-way
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A code snippets manager for your terminal
  dev_url: https://github.com/out-of-cheese-error/the-way

extra:
  recipe-maintainers:
    - danielnachun
